[tool.mypy]
strict = true
check_untyped_defs = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 100

[tool.pycln]
expand_stars = true
verbose = true
all = true
no_gitignore = false

[tool.nbqa.addopts]
isort = ["-l", "100", "--profile", "black", "--multi-line", "3", "--tc", "--up"]
black = ["-t", "py38", "-l", "100"]
pyupgrade = ["--py37-plus"]
flake8 = [
    "--ignore", "E203,E402,E501,E731,W503,D107,D105",
    "--exclude", "__init__.py,.ipynb_checkpoints",
    "--max-line-length", "100"
]
